_config_version: 33

model:
  provider: xiaomi
  default: mimo-v2.5

group_sessions_per_user: true

display:
  platforms:
    feishu:
      show_reasoning: false
      streaming: true
      tool_progress: all
      interim_assistant_messages: true

platforms:
  feishu:
    require_mention: true

platform_toolsets:
  api_server:
    - web
  feishu:
    - web

web: {}
