"""phase e pipeline

Revision ID: 20260815_0017
Revises: 20260811_0016
Create Date: 2026-08-17 10:22:43.269217
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260815_0017'
down_revision: Union[str, None] = '20260811_0016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'event_key', name='uq_notification_outbox_event')
    )
    op.create_index('ix_notification_outbox_claim', 'notification_outbox', ['status', 'next_attempt_at', 'id'], unique=False)
    op.create_index(op.f('ix_notification_outbox_organization_id'), 'notification_outbox', ['organization_id'], unique=False)
    op.create_index(op.f('ix_notification_outbox_status'), 'notification_outbox', ['status'], unique=False)
    op.create_table('pipeline_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('task_type', sa.String(length=40), nullable=False),
    sa.Column('schedule', sa.String(length=120), nullable=True),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('input_sources', sa.JSON(), nullable=False),
    sa.Column('output_format', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('creation_key', sa.String(length=160), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("output_format IN ('markdown')", name='ck_pipeline_tasks_output_format'),
    sa.CheckConstraint("status IN ('ready', 'paused', 'deleted')", name='ck_pipeline_tasks_status'),
    sa.CheckConstraint("task_type IN ('web_research', 'general')", name='ck_pipeline_tasks_type'),
    sa.CheckConstraint('revision > 0', name='ck_pipeline_tasks_revision_positive'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', 'creation_key', name='uq_pipeline_tasks_creation_key')
    )
    op.create_index(op.f('ix_pipeline_tasks_deleted_at'), 'pipeline_tasks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_pipeline_tasks_next_run_at'), 'pipeline_tasks', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_pipeline_tasks_organization_id'), 'pipeline_tasks', ['organization_id'], unique=False)
    op.create_index('ix_pipeline_tasks_owner_list', 'pipeline_tasks', ['organization_id', 'user_id', 'updated_at', 'id'], unique=False)
    op.create_index('ix_pipeline_tasks_schedule', 'pipeline_tasks', ['next_run_at', 'id'], unique=False, postgresql_where=sa.text("status = 'ready'"), sqlite_where=sa.text("status = 'ready'"))
    op.create_index(op.f('ix_pipeline_tasks_status'), 'pipeline_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_tasks_user_id'), 'pipeline_tasks', ['user_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('trigger_kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_by', sa.String(length=100), nullable=True),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'failed', 'cancelled', 'missed')", name='ck_pipeline_runs_status'),
    sa.CheckConstraint("trigger_kind IN ('scheduled', 'manual')", name='ck_pipeline_runs_trigger_kind'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['pipeline_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'task_id', 'idempotency_key', name='uq_pipeline_runs_idempotency'),
    sa.UniqueConstraint('organization_id', 'task_id', 'scheduled_for', name='uq_pipeline_runs_schedule')
    )
    op.create_index('ix_pipeline_runs_claim', 'pipeline_runs', ['status', 'scheduled_for', 'lease_expires_at', 'id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_lease_expires_at'), 'pipeline_runs', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_organization_id'), 'pipeline_runs', ['organization_id'], unique=False)
    op.create_index('ix_pipeline_runs_owner', 'pipeline_runs', ['organization_id', 'user_id', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_scheduled_for'), 'pipeline_runs', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_task_id'), 'pipeline_runs', ['task_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_user_id'), 'pipeline_runs', ['user_id'], unique=False)
    op.create_table('pipeline_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['pipeline_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'run_id', 'version', name='uq_pipeline_outputs_run_version')
    )
    op.create_index(op.f('ix_pipeline_outputs_organization_id'), 'pipeline_outputs', ['organization_id'], unique=False)
    op.create_index('ix_pipeline_outputs_owner', 'pipeline_outputs', ['organization_id', 'user_id', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_pipeline_outputs_run_id'), 'pipeline_outputs', ['run_id'], unique=False)
    op.create_index(op.f('ix_pipeline_outputs_task_id'), 'pipeline_outputs', ['task_id'], unique=False)
    op.create_index(op.f('ix_pipeline_outputs_user_id'), 'pipeline_outputs', ['user_id'], unique=False)
    op.create_table('dashboard_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('output_id', sa.Integer(), nullable=False),
    sa.Column('regeneration_run_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('change_request', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'changes_requested', 'regenerating', 'superseded')", name='ck_dashboard_decisions_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['output_id'], ['pipeline_outputs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regeneration_run_id'], ['pipeline_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['pipeline_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_decisions_organization_id'), 'dashboard_decisions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_dashboard_decisions_output_id'), 'dashboard_decisions', ['output_id'], unique=False)
    op.create_index('ix_dashboard_decisions_owner', 'dashboard_decisions', ['organization_id', 'user_id', 'status', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_dashboard_decisions_regeneration_run_id'), 'dashboard_decisions', ['regeneration_run_id'], unique=False)
    op.create_index(op.f('ix_dashboard_decisions_run_id'), 'dashboard_decisions', ['run_id'], unique=False)
    op.create_index(op.f('ix_dashboard_decisions_status'), 'dashboard_decisions', ['status'], unique=False)
    op.create_index(op.f('ix_dashboard_decisions_task_id'), 'dashboard_decisions', ['task_id'], unique=False)
    op.create_index(op.f('ix_dashboard_decisions_user_id'), 'dashboard_decisions', ['user_id'], unique=False)
    op.create_table('decision_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("action IN ('approve', 'reject', 'regenerate')", name='ck_decision_actions_action'),
    sa.ForeignKeyConstraint(['decision_id'], ['dashboard_decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'decision_id', 'idempotency_key', name='uq_decision_actions_idempotency')
    )
    op.create_index(op.f('ix_decision_actions_decision_id'), 'decision_actions', ['decision_id'], unique=False)
    op.create_index(op.f('ix_decision_actions_organization_id'), 'decision_actions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_decision_actions_user_id'), 'decision_actions', ['user_id'], unique=False)
    permissions = sa.table(
        'permissions',
        sa.column('id', sa.Integer()),
        sa.column('code', sa.String()),
        sa.column('description', sa.String()),
    )
    roles = sa.table('roles', sa.column('id', sa.Integer()), sa.column('name', sa.String()))
    pipeline_permissions = (
        ('pipeline:read', 'Read owned pipeline tasks and outputs'),
        ('pipeline:write', 'Create and update owned pipeline tasks'),
        ('pipeline:run', 'Run owned pipeline tasks'),
        ('pipeline:observe', 'Observe pipeline operational metadata'),
        ('decisions:read', 'Read owned dashboard decisions'),
        ('decisions:decide', 'Decide owned dashboard decisions'),
    )
    for code, description in pipeline_permissions:
        op.execute(
            sa.text(
                'INSERT INTO permissions (code, description) VALUES (:code, :description) '
                'ON CONFLICT (code) DO NOTHING'
            ).bindparams(code=code, description=description)
        )
    role_codes = {
        'admin': tuple(code for code, _ in pipeline_permissions),
        'manager': tuple(code for code, _ in pipeline_permissions if code != 'pipeline:observe'),
        'user': tuple(code for code, _ in pipeline_permissions if code != 'pipeline:observe'),
    }
    for role_name, codes in role_codes.items():
        role_row = op.get_bind().execute(sa.select(roles.c.id).where(roles.c.name == role_name)).first()
        if role_row is None:
            continue
        for code in codes:
            permission_row = op.get_bind().execute(
                sa.select(permissions.c.id).where(permissions.c.code == code)
            ).first()
            if permission_row is None:
                continue
            op.execute(
                sa.text(
                    'INSERT INTO role_permissions (role_id, permission_id) VALUES (:role_id, :permission_id) '
                    'ON CONFLICT (role_id, permission_id) DO NOTHING'
                ).bindparams(role_id=role_row[0], permission_id=permission_row[0])
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text(
            "DELETE FROM role_permissions WHERE permission_id IN "
            "(SELECT id FROM permissions WHERE code IN "
            "('pipeline:read', 'pipeline:write', 'pipeline:run', 'pipeline:observe', "
            "'decisions:read', 'decisions:decide'))"
        )
    )
    op.execute(
        sa.text(
            "DELETE FROM permissions WHERE code IN "
            "('pipeline:read', 'pipeline:write', 'pipeline:run', 'pipeline:observe', "
            "'decisions:read', 'decisions:decide') "
            "AND id NOT IN (SELECT DISTINCT permission_id FROM role_permissions)"
        )
    )
    op.drop_index(op.f('ix_decision_actions_user_id'), table_name='decision_actions')
    op.drop_index(op.f('ix_decision_actions_organization_id'), table_name='decision_actions')
    op.drop_index(op.f('ix_decision_actions_decision_id'), table_name='decision_actions')
    op.drop_table('decision_actions')
    op.drop_index(op.f('ix_dashboard_decisions_user_id'), table_name='dashboard_decisions')
    op.drop_index(op.f('ix_dashboard_decisions_task_id'), table_name='dashboard_decisions')
    op.drop_index(op.f('ix_dashboard_decisions_status'), table_name='dashboard_decisions')
    op.drop_index(op.f('ix_dashboard_decisions_run_id'), table_name='dashboard_decisions')
    op.drop_index(op.f('ix_dashboard_decisions_regeneration_run_id'), table_name='dashboard_decisions')
    op.drop_index('ix_dashboard_decisions_owner', table_name='dashboard_decisions')
    op.drop_index(op.f('ix_dashboard_decisions_output_id'), table_name='dashboard_decisions')
    op.drop_index(op.f('ix_dashboard_decisions_organization_id'), table_name='dashboard_decisions')
    op.drop_table('dashboard_decisions')
    op.drop_index(op.f('ix_pipeline_outputs_user_id'), table_name='pipeline_outputs')
    op.drop_index(op.f('ix_pipeline_outputs_task_id'), table_name='pipeline_outputs')
    op.drop_index(op.f('ix_pipeline_outputs_run_id'), table_name='pipeline_outputs')
    op.drop_index('ix_pipeline_outputs_owner', table_name='pipeline_outputs')
    op.drop_index(op.f('ix_pipeline_outputs_organization_id'), table_name='pipeline_outputs')
    op.drop_table('pipeline_outputs')
    op.drop_index(op.f('ix_pipeline_runs_user_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_task_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_status'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_scheduled_for'), table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_owner', table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_organization_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_lease_expires_at'), table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_claim', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_pipeline_tasks_user_id'), table_name='pipeline_tasks')
    op.drop_index(op.f('ix_pipeline_tasks_status'), table_name='pipeline_tasks')
    op.drop_index('ix_pipeline_tasks_schedule', table_name='pipeline_tasks', postgresql_where=sa.text("status = 'ready'"), sqlite_where=sa.text("status = 'ready'"))
    op.drop_index('ix_pipeline_tasks_owner_list', table_name='pipeline_tasks')
    op.drop_index(op.f('ix_pipeline_tasks_organization_id'), table_name='pipeline_tasks')
    op.drop_index(op.f('ix_pipeline_tasks_next_run_at'), table_name='pipeline_tasks')
    op.drop_index(op.f('ix_pipeline_tasks_deleted_at'), table_name='pipeline_tasks')
    op.drop_table('pipeline_tasks')
    op.drop_index(op.f('ix_notification_outbox_status'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_organization_id'), table_name='notification_outbox')
    op.drop_index('ix_notification_outbox_claim', table_name='notification_outbox')
    op.drop_table('notification_outbox')
    # ### end Alembic commands ###
