import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { KnowledgeService } from "../api/services/knowledgeService";
import { asObject, errorStatus, readArray, readNumber, readString, type PageCache } from "./pageUtils";

type KnowledgePageProps = { cache: PageCache; organizationId: number | null; service: KnowledgeService };
type PageStatus = "loading" | "empty" | "error" | "forbidden" | "success";
type Entry = { id: number; title: string; type: string; status: string; updatedAt: string };
type Collection = { id: number; name: string };
function mapEntry(value: unknown, index: number): Entry { const item = asObject(value); return { id: readNumber(item.id, index + 1), title: readString(item.title, readString(item.name, `知识条目 ${index + 1}`)), type: readString(item.type, readString(item.resource_type, "document")), status: readString(item.status, item.archived ? "archived" : "active"), updatedAt: readString(item.updated_at, readString(item.updatedAt)) }; }
function mapCollection(value: unknown, index: number): Collection { const item = asObject(value); return { id: readNumber(item.id, index + 1), name: readString(item.name, `知识目录 ${index + 1}`) }; }
function items(value: unknown) { const item = asObject(value); return Array.isArray(value) ? value : readArray(item.items); }
function messageForError(error: unknown) { return errorStatus(error) === 403 ? "没有知识库访问权限" : "知识库加载失败"; }

export function KnowledgePage({ cache, organizationId, service }: KnowledgePageProps) {
  const [entries, setEntries] = useState<Entry[]>([]); const [collections, setCollections] = useState<Collection[]>([]); const [collectionId, setCollectionId] = useState<number | null>(null); const [status, setStatus] = useState<PageStatus>(organizationId === null ? "forbidden" : "loading"); const [errorMessage, setErrorMessage] = useState<string | null>(organizationId === null ? "没有知识库访问权限" : null); const [title, setTitle] = useState(""); const [pending, setPending] = useState<string | null>(null); const [progress, setProgress] = useState<number | null>(null); const fileRef = useRef<HTMLInputElement>(null); const cacheKey = useMemo(() => ["knowledge", "entries"], []);
  const loadEntries = useCallback(async () => { if (organizationId === null) { setStatus("forbidden"); setErrorMessage("没有知识库访问权限"); return; } setStatus("loading"); setErrorMessage(null); try { const cached = cache.get<Entry[]>(organizationId, cacheKey); const [entryPayload, collectionPayload] = await Promise.all([cached ? Promise.resolve({ items: cached }) : service.listEntries(), service.listCollections()]); const next = cached ?? items(entryPayload).map(mapEntry); const nextCollections = items(collectionPayload).map(mapCollection); if (!cached) cache.set(organizationId, cacheKey, next); setEntries(next); setCollections(nextCollections); setCollectionId((current) => current ?? nextCollections[0]?.id ?? null); setStatus(next.length ? "success" : "empty"); } catch (error) { setStatus(errorStatus(error) === 403 ? "forbidden" : "error"); setErrorMessage(messageForError(error)); setEntries([]); setCollections([]); setCollectionId(null); } }, [cache, cacheKey, organizationId, service]);
  useEffect(() => { const timer = window.setTimeout(() => void loadEntries(), 0); return () => window.clearTimeout(timer); }, [loadEntries]);
  async function createEntry(event: React.FormEvent) { event.preventDefault(); const value = title.trim(); if (!value) return; setPending("create"); setErrorMessage(null); try { const created = mapEntry(await service.createEntry({ title: value, type: "document" }), entries.length); const next = [...entries, created]; setEntries(next); setTitle(""); setStatus("success"); if (organizationId !== null) { cache.invalidateOrganization(organizationId); cache.set(organizationId, cacheKey, next); } } catch (error) { setErrorMessage(error instanceof Error ? error.message : "知识条目创建失败"); } finally { setPending(null); } }
  async function uploadFile(file: File) { if (collectionId === null) { setErrorMessage("请先选择知识目录"); return; } setPending("upload"); setProgress(0); setErrorMessage(null); try { const form = new FormData(); form.append("title", file.name); form.append("collection_id", String(collectionId)); form.append("file", file); const created = mapEntry(await service.uploadEntry(form, (loaded, total) => setProgress(total ? Math.round((loaded / total) * 100) : null)), entries.length); const next = [...entries, created]; setEntries(next); setStatus("success"); if (organizationId !== null) { cache.invalidateOrganization(organizationId); cache.set(organizationId, cacheKey, next); } } catch (error) { setErrorMessage(error instanceof Error ? error.message : "文件上传失败"); } finally { setPending(null); setProgress(null); if (fileRef.current) fileRef.current.value = ""; } }
  async function archiveEntry(entry: Entry) { setPending(`archive-${entry.id}`); setErrorMessage(null); try { await service.archiveEntry(entry.id); const next = entries.filter((item) => item.id !== entry.id); setEntries(next); setStatus(next.length ? "success" : "empty"); if (organizationId !== null) { cache.invalidateOrganization(organizationId); cache.set(organizationId, cacheKey, next); } } catch (error) { setErrorMessage(error instanceof Error ? error.message : "知识条目归档失败"); } finally { setPending(null); } }
  const canUse = organizationId !== null && status !== "forbidden";
  return <main aria-labelledby="knowledge-title" className="page-view knowledge-page"><header className="page-header"><div><h1 id="knowledge-title">知识库</h1><p>管理企业知识条目并上传资料。</p></div><button disabled={!canUse || status === "loading"} onClick={() => void loadEntries()} type="button">刷新知识库</button></header>{errorMessage ? <p className="error-message" role="alert">{errorMessage}</p> : null}{status === "loading" ? <p>正在加载知识库</p> : null}{status === "empty" ? <p>暂无知识条目</p> : null}<section aria-label="创建知识条目"><form onSubmit={createEntry}><label htmlFor="knowledge-title-input">条目名称</label><input id="knowledge-title-input" onChange={(event) => setTitle(event.currentTarget.value)} value={title} /><button disabled={!canUse || pending !== null || !title.trim()} type="submit">创建条目</button></form><label htmlFor="knowledge-collection-input">知识目录</label><select aria-label="知识目录" disabled={!canUse || pending !== null || !collections.length} id="knowledge-collection-input" onChange={(event) => setCollectionId(Number(event.currentTarget.value))} value={collectionId ?? ""}><option value="">请选择知识目录</option>{collections.map((collection) => <option key={collection.id} value={collection.id}>{collection.name}</option>)}</select><label htmlFor="knowledge-file-input">上传文件</label><input accept="*/*" disabled={!canUse || pending !== null || collectionId === null} id="knowledge-file-input" onChange={(event) => { const file = event.currentTarget.files?.[0]; if (file) void uploadFile(file); }} ref={fileRef} type="file" />{progress !== null ? <progress aria-label="上传进度" max="100" value={progress}>{progress}%</progress> : null}</section><section aria-label="知识条目列表">{entries.length ? <ul>{entries.map((entry) => <li key={entry.id}><article><h2>{entry.title}</h2><p>{entry.type} · {entry.status}</p>{entry.updatedAt ? <time>{entry.updatedAt}</time> : null}<button aria-label={`归档 ${entry.title}`} disabled={!canUse || pending !== null} onClick={() => void archiveEntry(entry)} type="button">归档</button></article></li>)}</ul> : null}</section></main>;
}
